MVC_Shop/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_Shop;
using MVC_Shop.Services;
using MVC_Shop.ViewModels;
using MVC_Shop.ViewModels.Product;



namespace PD421_MVC_Shop.Controllers
{
    public class CartController : Controller
    {
        private readonly AppDbContext _context;

        public CartController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            // Session items
            var cartItems = HttpContext.Session.GetCartItems();
            var itemsId = cartItems.Select(i => i.ProductId);

            // Products and create cartVM
            var products = _context.Products
                .Where(p => itemsId.Contains(p.Id))
                .ToList();

            var productsCart = products.Select(p => new ProductCartVM
            {
                Product = p,
                Count = cartItems.FirstOrDefault(i => i.ProductId == p.Id)!.Count
            });

            return View(productsCart);
        }

        public IActionResult IncreaseCount(int productId)
        {
            var amount = _context.Products
                .FirstOrDefault(p => p.Id == productId)?.Count;

            HttpContext.Session.IncreaseCount(productId, amount ?? 0);
            return RedirectToAction("Index");
        }

        public IActionResult DecreaseCount(int productId)
        {
            HttpContext.Session.DecreaseCount(productId);
            return RedirectToAction("Index");
        }

        public IActionResult Checkout(int productId)
        {
            var cartItems = HttpContext.Session.GetCartItems();
            var itemsId = cartItems.Select(i => i.ProductId);

            var products = _context.Products
                .Where(p => itemsId.Contains(p.Id))
                .AsNoTracking()
                .ToList();

            foreach (var product in products)
            {
                int count = cartItems.Find(i => i.ProductId == product.Id)?.Count ?? 0;
                if (count > 0)
                {
                    product.Count -= count;
                    _context.Products.Update(product);
                }
            }
            _context.SaveChanges();
            HttpContext.Session.ClearCart();

            return RedirectToAction("Index", "Home");
        }
    }
}

MVC_Shop/Controllers/PlanetController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC_Shop.Controllers
{
    public class PlanetController : Controller
    {
        public IActionResult BestPlaces()
        {
            return View();
        }
    }
}

MVC_Shop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Shop.Models;
using MVC_Shop.Repositories.Category;
using MVC_Shop.Repositories.Product;
using MVC_Shop.ViewModels.Product;

namespace MVC_Shop.Controllers
{
    [Authorize(Roles = "admin")]
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly AppDbContext _context;
        private IWebHostEnvironment _webHostEnvironment;

        public ProductController(AppDbContext context, IProductRepository productRepository, 
            ICategoryRepository categoryRepository, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        private string? SaveImage(IFormFile? image)
        {
            if(image == null || image.Length == 0)
            {
                return null;
            }
            string[] types = image.ContentType.Split('/'); 
            if (types[0] != "image" || types.Length != 2)
            {
                return null;
            }
            string imageName = $"{ Guid.NewGuid().ToString()}.{types[1]}";
            string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", imageName);
            
            using (var stream = new FileStream(imagePath, FileMode.Create))
            {
                using (var imageStream = image.OpenReadStream())
                {
                    imageStream.CopyTo(stream);
                }
            }
            return imageName;
        }
        private void DeleteImage(string? imageName)
        {
            if (string.IsNullOrEmpty(imageName))
                return;

            string fullPath = Path.Combine(_webHostEnvironment.WebRootPath, "images", imageName);
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
            }
        }
        public async Task<IActionResult> Index(int page = 1)
        {
            int pageSize = Settings.PaginationPageSize;

            var productsQuery = _productRepository.Products.Include(p => p.Category);

            int totalItems = await productsQuery.CountAsync();

            var products = await productsQuery
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            var model = new ProductVM
            {
                Products = products,
                CurrentPage = page,
                PageSize = pageSize,
                TotalItems = totalItems
            };

            return View(model);
        }



        public async Task<IActionResult> ByCategory(string categoryName)
        {
            var products = await _productRepository.GetProductsByCategoryNameAsync(categoryName);
            return View("Index", products);
        }

        public async Task<IActionResult> ByPrice(float min, float max)
        {
            var products = await _productRepository.GetProductsByPriceRangeAsync(min, max);
            return View("Index", products);
        }

        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_categoryRepository.Categories, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] CreateProductVM viewModel)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = new SelectList(_categoryRepository.Categories, "Id", "Name");
                return View(viewModel);
            }
            if (await _productRepository.IsExistAsync(viewModel.Name))
            {
                ModelState.AddModelError("UniqueNameError", $"Товар з іменем '{viewModel.Name}' вже існує!");
                ViewBag.Categories = new SelectList(_categoryRepository.Categories, "Id", "Name");
                return View(viewModel);

            }
            var product = new Product
            {
                Name = viewModel.Name,
                Description = viewModel.Description,
                Price = viewModel.Price ?? 0,
                Image = SaveImage(viewModel.Image),
                Count = viewModel.Count ?? 0,
                CategoryId = viewModel.CategoryId
            };
            await _productRepository.CreateAsync(product);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(int id)
        {
            var model = await _productRepository.GetByIdAsync(id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            var viewModel = new UpdateProductVM
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                Price = model.Price,
                Image = model.Image,
                Count = model.Count,
                CategoryId = model.CategoryId
            };
            ViewBag.Categories = new SelectList(_categoryRepository.Categories, "Id", "Name", model.CategoryId);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(UpdateProductVM viewModel)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = new SelectList(_categoryRepository.Categories, "Id", "Name", viewModel.CategoryId);
                return View(viewModel);
            }

            if (await _productRepository.IsExistAsync(viewModel.Name, viewModel.Id))
            {
                ModelState.AddModelError("UniqueNameError", $"Товар з іменем '{viewModel.Name}' вже існує!");
                ViewBag.Categories = new SelectList(_categoryRepository.Categories, "Id", "Name", viewModel.CategoryId);
                return View(viewModel);
            }

            var model = await _productRepository.GetByIdAsync(viewModel.Id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }

            if (viewModel.NewImage != null && viewModel.NewImage.Length > 0)
            {
                DeleteImage(model.Image);
                model.Image = SaveImage(viewModel.NewImage);
            }

            model.Name = viewModel.Name;
            model.Description = viewModel.Description;
            model.Price = viewModel.Price ?? 0;
            model.Count = viewModel.Count ?? 0;
            model.CategoryId = viewModel.CategoryId;

            _productRepository.Update(model);
            await _productRepository.SaveChangesAsync();

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Delete(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product != null)
            {
                DeleteImage(product.Image);
                await _productRepository.DeleteAsync(id);
            }
            return RedirectToAction("Index");
        }
        
    }
}

MVC_Shop/Controllers/UsersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MVC_Shop.Models;
using MVC_Shop.Repositories.Users;
using MVC_Shop.ViewModels.Users;

namespace MVC_Shop.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUsersRepository _usersRepository;
        private readonly UserManager<ApplicationUser> _userManager;
        private const int PageSize = Settings.PaginationPageSize;

        public UsersController(IUsersRepository usersRepository, UserManager<ApplicationUser> userManager)
        {
            _usersRepository = usersRepository;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var usersQuery = _usersRepository.Users;

            int totalUsers = usersQuery.Count();
            var users = usersQuery
                .OrderBy(u => u.UserName)
                .Skip((page - 1) * PageSize)
                .Take(PageSize)
                .ToList();


            var userVMs = new List<UserVM>();
            foreach (var user in users)
            {
                var roles = await _userManager.GetRolesAsync(user);
                userVMs.Add(new UserVM
                {
                    Id = user.Id,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    UserName = user.UserName,
                    Email = user.Email,
                    Role = roles.FirstOrDefault() ?? "No Role"
                });
            }

            var vm = new UserListVM
            {
                Users = userVMs,
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(totalUsers / (double)PageSize)
            };

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest();

            await _usersRepository.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeRole(string userId, string newRole)
        {
            if (string.IsNullOrEmpty(userId) || string.IsNullOrEmpty(newRole))
                return BadRequest();

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null) return NotFound();

            var currentRoles = await _userManager.GetRolesAsync(user);

            var removeResult = await _userManager.RemoveFromRolesAsync(user, currentRoles);
            if (!removeResult.Succeeded)
            {
                TempData["Error"] = "Не вдалося видалити старі ролі.";
                return RedirectToAction(nameof(Index));
            }

            var addResult = await _userManager.AddToRoleAsync(user, newRole);
            if (!addResult.Succeeded)
            {
                TempData["Error"] = "Не вдалося додати нову роль.";
            }
            else
            {
                TempData["Success"] = "Роль користувача успішно змінена.";
            }

            return RedirectToAction(nameof(Index));
        }

    }
}

MVC_Shop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject IHttpContextAccessor HttpContextAccessor
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Shop</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/css/products.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_Shop.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MY SHOP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Головна сторінка</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">Про нас</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Language" asp-action="Favorite">Улюблена мова</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planet" asp-action="BestPlaces">Місця планети</a>
                        </li>
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Категорії</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Каталог</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Користувачі</a>
                            </li>
                        }
                    </ul>
                </div>
                <div  class="me-2">
                    <partial name="_LoginPartial" />
                </div>
                </div>

            <div class="nav-cart d-flex align-items-center ms-3">
                <a asp-controller="Cart" class="text-dark text-decoration-none position-relative">
                    <i class="bi bi-cart3 fs-4"></i>
                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                        @HttpContextAccessor.HttpContext.Session.CartCount()
                    </span>
                </a>
            </div>


        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MVC_Shop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @* <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>